version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-example
      MYSQL_USER: user_rw
      MYSQL_PASSWORD: user_rw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: dev-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
